before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: CTlsWpm46VAonOVeLdbg5uYN1rOJPXwlGQMNNqrYSKMHSVV89ZipnDYhtz1PCMcJGT5qw256kxJW3Lx5zbgHH34gGtu8jPtNBTHRIC+eduvgyt1Z6m0ddaYKOhECN/zlpabBCpTB5NQ9IspisL/EOSXsh7TGfPj/7IHURzSXNDRcCToQuE9xq+RtlKZA3Hgmhye/4wCIR+PtNOIPCZvKB0I2xLTq1wrPRU++B4vuDBj1IJ9Xg9x1xlZtUAKy+q6/ti91QlfImFarPcJoFZTTMY+pZaKiUE0/Hr3A6hrSeB4s8svwRrOBKvXUi6I86pht8H1VYXxrPlIZNQs5eMi8Ks87JwRGtiPBPaT0zDTd7vnrnZ933BcKAdk3wR0A4aslVZGLOV21Zc2GR4JyZEtVjNXpyLmIppI8tV/J0fnTpNeJBhMdWmGjVTgDNlCFDQTQnJKZthXSaPt98eEC41OTIEnYeps883SsgUQO4KKxu2VHK8/5VbSMvwEeuHNVnYuf9NGjKa96TA22LTzLunHGt4IzykNDlA6O+/4fZ27V4WhJ+U2A7FpD3Qe71oabuSeoWMUtl+lwZic5mQlXa6L6hXKvOhYU6oD/WzITQs6/qjJRscyEx2b3nIuZ0iXXJ8+QpZreowggwzCwdXij1dnVk46/3Z58Ru0CAHs5YpE+F4w= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
